### ISSUE TITLE
can't delete accounts

### ISSUE THREAD

**Issue by gwlegion** [YunoHost-Apps/2FAuth_ynh#12]
Matériel: Raspberry Pi à la maison
Version de YunoHost: 4.3.6.3 (stable).
J’ai accès à mon serveur : En SSH | Par la webadmin
Êtes-vous dans un contexte particulier ou avez-vous effectué des modificiations particulières sur votre instance ? : non

hi ... so, the code generation is now working ... 

but still got another problem : i can't delete any account .

when i try, i got the confirmation popup, but when i click ok, nothing appen. 

oppened an issue on the 2fauth github too ... the dev is very cool !

https://github.com/Bubka/2FAuth/issues/87

**Comment by Bubka** [comment]
Hi,

The request at fault is a DELETE with a query string parameter: `DELETE https://yunohost.local/api/v1/twofaccounts?ids=2,1`
The response code is 422 because the `ids` parameter is missing in the Laravel request object, as if NGINX had removed the parameter.

This works well using apache2. Does NGINX has some sort of limitation with the DELETE verb related to the yunohost package configuration?

**Comment by ericgaspar** [comment]
@Bubka Thanks for looking into this!

I'm also investigating the issue... The culprit could also be access to the API: we may need to set the authorization : https://github.com/YunoHost/example_ynh/blob/1c682f5d5287309ace7c8d05dee7581530d1479e/scripts/install#L394-L397

@gwlegion In the meantime you can try this:
in the NGINX config file `/etc/nginx/conf.d/[DOMAIN]/2fauth.conf` change `try_files $uri $uri/ /index.php;` to `try_files $uri $uri/ /index.php?$query_string;`
and then restart service `sudo service nginx restart`

**Comment by gwlegion** [comment]
i got a 404 error when i try this

**Comment by ericgaspar** [comment]
@gwlegion I can't reproduce your issue.
I have installed 2FAuth (from testing branch), created an account and removed this account.

**Comment by gwlegion** [comment]
> Thanks! This settings are in the tesing branch now.

got someone to test it !
