### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Veehem** [YunoHost-Apps/2FAuth_ynh#2]
FR: Après l'installation dans un sous domaine (pas de problème), le réglage du nom d'utilisateur et du mot de passe, il n'est pas possible d'entrer dans l'administration. Je l'ai désinstallé et réinstallé Même problème. Et si j'essaie de réinitialiser le mot de passe, j'ai un message disant : An error occured : Cannot send message without a sender address

EN: After installation in a sub domain (no problem), setting username & password it's not possible to enter in the admin. I've disinstalled it and reinstalled it Same problem. And if I try to reset the passw, I've a message saying : An error occured: Cannot send message without a sender address

**Comment by ericgaspar** [comment]
The new version 3.0.0 seems to fix this issue.
If you want to test:
```
sudo yunohost app install https://github.com/YunoHost-Apps/2fauth_ynh/tree/testing 
```

**Comment by ericgaspar** [comment]
#3 should fix the issue. Let me know.

**Comment by Veehem** [comment]
Sorry but I am not able (I don't have the skills) to use anything else than the interface installer of YunoHost and it still provides the version 2.1.0~ynh2

**Comment by ericgaspar** [comment]
Give the app a bit of time to go through the validation process...

**Comment by Veehem** [comment]
OK
