### ISSUE TITLE
Can´t register webauthn device 

### ISSUE THREAD

**Issue by pjpmosteiro** [YunoHost-Apps/2FAuth_ynh#34]
### Describe the bug

Can´t enroll webauth device (yubikey or windows FIDO)

### Context

- Hardware: VPS --  Connecting from Windows 11 and Android, Vivaldi and Edge browsers. All extensions disabled.
- YunoHost version: 11.1.18
- I have access to my server: SSH/WebAdmin/direct
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - Using cloudflare tunnel for internal applications and custom certificates
- Using, or trying to install package version/branch: Latest on stable branch
- If upgrading, current package version: ----

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. Login on 2FAuth interface
   2. Go to Settings
   3. Select the "WebAuth" tab
   4.  Click on "Register new device"

### Logs

![image](https://user-images.githubusercontent.com/15787529/236189592-5ff89120-e230-46c4-b62c-c996413b42e6.png)

**Comment by stepcellwolf** [comment]
Hi same here I'm having this issue with yubikey and iPhone. I have reported the issue here too: https://github.com/Bubka/2FAuth/issues/218

**Comment by CptNemo1337** [comment]
I have the same error here and can't figure out how to fix

**Comment by ericgaspar** [comment]
I have added https://github.com/Bubka/2FAuth_ynh/commit/65032cd7e661ed8661269bcab12a79fcc3e48dfd modifications to `.en` file in  #38

**Comment by pjpmosteiro** [comment]
I edited the .env file as @Bubka says, but same error, also with new accounts. What I might be doing wrong?

**Comment by Bubka** [comment]
The app cache needs to be refreshed by running `php artisan config:clear` in a terminal.
If you can't run the php command, remove the content of `[2FAuth_install_dir]\storage\framework\cache\data\`.

**Comment by pjpmosteiro** [comment]
> The app cache needs to be refreshed by running `php artisan config:clear` in a terminal. If you can't run the php command, remove the content of `[2FAuth_install_dir]\storage\framework\cache\data\`.

Oops, I knew I was forgetting something :D 

Issue solved, it seems.
