### ISSUE TITLE
Upgrade failed from 4.1.0~ynh1 to 4.1.0~ynh3

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/2FAuth_ynh#40]
### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: VPS bought online
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 4.1.0~ynh1

### Steps to reproduce
I just hit the upgrade button in webadmin UI.

### Expected behavior

Upgrade should run successfully.

### Logs
https://paste.yunohost.org/raw/runobilese

**Comment by mat-mo** [comment]
I face the same issue - https://paste.yunohost.org/raw/piqebatozi

**Comment by CodeShakingSheep** [comment]
The issue is resolved for me with the fix from yesterday. Thanks @Thovi98. I could successfully upgrade to 4.1.0~ynh4. So, I'll close this.
