### ISSUE TITLE
bad php version

### ISSUE THREAD

**Issue by gwlegion** [YunoHost-Apps/2FAuth_ynh#9]
Matériel: Raspberry Pi à la maison
Version de YunoHost: 4.3.6.3 (stable).
J’ai accès à mon serveur : En SSH | Par la webadmin
Êtes-vous dans un contexte particulier ou avez-vous effectué des modificiations particulières sur votre instance ? : non

got some strange errors ... when i create a new account, first, codes are good, but, when i accept the new accound codes gone bad ... the secret is wrong. when i manually correct the secred, code are good.

and i can't delete any account.

the 2fauth creator tell me it was designed to work with php 7.4, but when i look, it's configured to php 8.0

**Comment by gwlegion** [comment]
tried with 7.4 forced, still the same errors ... got a problem with this package

**Comment by Bubka** [comment]
Hi,
it's a 2FAuth bug introduced in the latest release (v3.1.0): https://github.com/Bubka/2FAuth/issues/86

About PHP version: 2FAuth requires __at least__ PHP7.4, so PHP8.0 is supported.

**Comment by gwlegion** [comment]
ok, this version generate valide codes ... got another problem, opening another issue
